name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  pytests:
    strategy:
      matrix:
        systems: [ "ubuntu-latest", "windows-latest" ]
        python-version: [3.8]

    runs-on: ${{ matrix.systems }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run block_tests
      run:
        python -m unittest tests/block_tests.py

    - name: Run node_tests
      run:
        python -m unittest tests/node_tests.py